export enum ScholarshipEnum {
    zero = '0',
    ten = '10',
    fifteen = '15',
    twenty = '20',
    twentyFive = '25',
    thirty = '30',
    thirtyFive = '35',
    forty = '40',
    fortyFive = '45',
    fifty = '50',
    fiftyFive = '55',
    sixty = '60',
    seventy = '70',
    eighty = '80',
    ninety = '90',
    hundred = '100',
    apoyoTrabajador = 'APOYO TRABAJADOR',
    orfandad = 'ORFANDAD'
}