export enum ScholarshipEnum {
  zero = '0',
  five = '5',
  ten = '10',
  fifteen = '15',
  twenty = '20',
  twentyFive = '25',
  thirty = '30',
  thirtyFive = '35',
  forty = '40',
  fortyFive = '45',
  fifty = '50',
  fiftyFive = '55',
  sixty = '60',
  apoyoTrabajador = 'APOYO TRABAJADOR',
  orfandad = 'ORFANDAD',
  patronato = 'PATRONATO',
  practicanteRH = 'PRACTICANTE RH',
}
