# Dockerfile
FROM node:18

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios para dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Generar cliente Prisma
RUN npx prisma generate



# Compilar el proyecto (NestJS en modo producción)
RUN npm run build

# Exponer el puerto
EXPOSE 3002

# Ejecutar la aplicación compilada
CMD ["npm", "run", "start:prod"]
