import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const data = [
  { name: 'LICENCIATURA EN PSICOLOGIA', program: 'LPS' },
  { name: 'LICENCIATURA EN DERECHO', program: 'LED' },
  { name: 'LICENCIATURA EN PEDAGOGIA', program: 'LPE' },
  { name: 'LICENCIATURA EN CIENCIAS POLITICAS Y GESTION PUBLICA', program: 'LCP' },
  { name: 'LICENCIATURA EN RELACIONES INTERNACIONALES', program: 'LRI' },
  { name: 'LICENCIATURA EN RELACIONES INTERNACIONALES Y ECONOMIA', program: 'RIEC' },
  { name: 'LICENCIATURA EN RELACIONES INTERNACIONALES Y CIENCIAS POLITICAS', program: 'RICP' },
  { name: 'LICENCIATURA EN IDIOMAS', program: 'LID' },
  { name: 'LICENCIATURA EN COMUNICACION', program: 'LCO' },

  { name: 'INGENIERIA EN CIVIL', program: 'ICI' },
  { name: 'INGENIERIA EN MECATRONICA', program: 'IME' },
  { name: 'INGENIERIA EN MECANICA INDUSTRIAL', program: 'IMI' },
  { name: 'INGENIERIA EN INDUSTRIAL Y DE SISTEMAS DE CALIDAD', program: 'IISCA' },
  { name: 'INGENIERIA EN SISTEMAS COMPUTACIONALES', program: 'ISC' },
  { name: 'INGENIERIA EN AMBIENTAL', program: 'IAM' },

  { name: 'LICENCIATURA EN DISENO DE MODAS Y TENDENCIAS INTERNACIONALES', program: 'LDM' },
  { name: 'LICENCIATURA EN DISENO INDUSTRIAL', program: 'LDI' },
  { name: 'LICENCIATURA EN DISENO GRAFICO', program: 'LDG' },
  { name: 'LICENCIATURA EN ANIMACION Y DISENO DIGITAL', program: 'LADD' },

  { name: 'LICENCIATURA EN COMUNICACION Y RELACIONES PUBLICAS', program: 'CORP' },
  { name: 'LICENCIATURA EN COMERCIO EXTERIOR', program: 'LCE' },
  { name: 'LICENCIATURA EN ECONOMIA Y FINANZAS', program: 'LEF' },
  { name: 'LICENCIATURA EN MERCADOTECNIA', program: 'LEM' },
  { name: 'LICENCIATURA EN MERCADOTECNIA Y PUBLICIDAD', program: 'LEMP' },
  { name: 'LICENCIATURA EN ADMINISTRACION DE EMPRESAS TURISTICAS', program: 'LAET' },
  { name: 'LICENCIATURA EN ADMINISTRACION DE EMPRESAS', program: 'LAE' },
  { name: 'LICENCIATURA EN ADMINISTRACION DE NEGOCIOS INTERNACIONALES', program: 'LANI' },
  { name: 'LICENCIATURA EN ADMINISTRACION Y MERCADOTECNIA', program: 'LAM' },
  { name: 'LICENCIATURA EN ARQUITECTURA', program: 'ARQ' },

  { name: 'LICENCIATURA EJECUTIVA EN GESTION EMPRESARIAL', program: 'LEGE' },
  { name: 'LICENCIATURA EJECUTIVA EN MERCADOTECNIA', program: 'LEMK' },
  { name: 'LICENCIATURA EJECUTIVA EN ADMINISTRACION DE NEGOCIOS INTERNACIONALES', program: 'LEANI' },
  { name: 'LICENCIATURA EJECUTIVA EN ADMINISTRACION Y MERCADOTECNIA', program: 'LEAM' },
  { name: 'LICENCIATURA EJECUTIVA EN MERCADOTECNIA Y PUBLICIDAD', program: 'LEMKP' },
  { name: 'LICENCIATURA EJECUTIVA EN COMERCIO EXTERIOR', program: 'LECE' },
  { name: 'LICENCIATURA EJECUTIVA EN DERECHO', program: 'LEDE' },

  { name: 'ESPECIALIDAD EN CRIMINALISTICA', program: 'EC' },
  { name: 'ESPECIALIDAD EN RELACIONES MERCANTILES INTERNACIONALES', program: 'ERMI' },
  { name: 'ESPECIALIDAD EN MARKETING DIGITAL', program: 'EMD' },
  { name: 'ESPECIALIDAD EN PROMOCION TURISTICA', program: 'EPT' },
  { name: 'ESPECIALIDAD EN PUBLICIDAD', program: 'EPU' },
  { name: 'ESPECIALIDAD EN ADMINISTRACION DE LA TECNOLOGIA EN LINEA', program: 'EATL' },
  { name: 'ESPECIALIDAD EN ADMINISTRACION DE OBRA', program: 'EAO' },
  { name: 'ESPECIALIDAD EN ANIMACION Y POST-PRODUCCION DIGITAL', program: 'EAPD' },
  { name: 'ESPECIALIDAD EN DOCENCIA DEL ESPANOL COMO LENGUA EXTRANJERA', program: 'EDELE' },

  { name: 'DIPLOMADO EN INVESTIGACION Y PLANEACION DE MEDIOS', program: 'DIPMD' },
  { name: 'DIPLOMADO EN CAMPANAS DE MARKETING Y PUBLICIDAD DIGITAL', program: 'DCMPD' },
  { name: 'DIPLOMADO EN COMERCIO EXTERIOR Y CONTRATOS INTERNACIONALES', program: 'DERMI' },
  { name: 'DIPLOMADO EN DERECHO ADUANERO Y MARCO JURIDICO DE LA COMPETENCIA ECONOMICA', program: 'DAMCE' },
  { name: 'DIPLOMADO EN CREATIVIDAD Y PUBLICIDAD', program: 'DEPU1' },
  { name: 'DIPLOMADO EN MERCADOTECNIA Y PUBLICIDAD', program: 'DEPU2' },
  { name: 'DIPLOMADO EN FRANCES', program: 'DEF' },
  { name: 'DIPLOMADO EN INGLES', program: 'DEI' },
  { name: 'DIPLOMADO EN INGLES PROFESIONAL', program: 'DIP' },
  { name: 'DIPLOMADO EN DISENO Y DESARROLLO DE PROYECTOS ACADEMICOS E INVESTIGACION', program: 'DDPAI' },
  { name: 'DIPLOMADO EN DISENO DE INTERIORES', program: 'DDI' },
  { name: 'DIPLOMADO EN FOTOGRAFIA', program: 'DIFO' },
  { name: 'DIPLOMADO EN GESTION EMPRESARIAL', program: 'DGE' },
  { name: 'DIPLOMADO EN DIRECCION DE EMPRESAS', program: 'DDE' },
  { name: 'DIPLOMADO EN ESTRATEGIAS DIDACTICAS Y METODOS DE ENSENANZA DE UNA L2', program: 'DEDME' },

  { name: 'MAESTRIA EN ADMINISTRACION Y DIRECCION DE EMPRESAS', program: 'MADE' },
  { name: 'MAESTRIA EN LINEA DE ADMINISTRACION Y DIRECCION DE EMPRESAS', program: 'MADEL' },
  { name: 'MAESTRIA EN ADMINISTRACION CON ESPECIALIDAD EN NEGOCIOS INTERNACIONALES', program: 'MAD' },
  { name: 'MAESTRIA EN ALTA DIRECCION', program: 'MADIR' },
  { name: 'MAESTRIA EN FINANZAS CORPORATIVAS', program: 'MFC' },
  { name: 'MAESTRIA EN GESTION DE LA CALIDAD', program: 'MGC' },
  { name: 'MAESTRIA EN GESTION DEL FACTOR Y CAPITAL HUMANO', program: 'MGFH' },
  { name: 'MAESTRIA EN IMPUESTOS', program: 'MI' },
  { name: 'MAESTRIA EN MERCADOTECNIA GLOBAL', program: 'MMG' },
  { name: 'MAESTRIA EN EDUCACION EN FORMACION DOCENTE', program: 'MEFD' },
  { name: 'MAESTRIA EN ENSENANZA DE LENGUAS EXTRANJERAS', program: 'MEL' },
  { name: 'MAESTRIA EN REDES DE COMPUTADORAS Y TECNOLOGIAS WEB', program: 'MARET' },

  { name: 'DOCTORADO EN ADMINISTRACION', program: 'DAD' },
  { name: 'DOCTORADO EN HUMANIDADES', program: 'DHU' },

  { name: 'SECUNDARIA BILINGUE', program: 'SIU' },
  { name: 'SECUNDARIA MULTICULTURAL', program: 'SIUM' },
  { name: 'BACHILLERATO BILINGUE', program: 'BIU' },
  { name: 'BACHILLERATO MULTICULTURAL', program: 'BIUM' },
];

export async function CareersSeeder() {
  await prisma.careers.createMany({
    data,
    skipDuplicates: true,
  });
}
