import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
export async function CitiesSeeder() {
	const stateMap = new Map<string, string>()
	const stateNames = [
		'MORELOS',
		'CIUDAD DE MEXICO',
		'GUERRERO',
		'ESTADO DE MEXICO',
		'AGUASCALIENTES',
		'BAJA CALIFORNIA',
		'BAJA CALIFORNIA SUR',
		'CAMPECHE',
		'CHIAPAS',
		'COAHUILA DE ZARAGOZA',
		'DURANGO',
		'GUANAJUATO',
		'HIDALGO',
		'JALISCO',
		'MICHOACAN',
		'NAYARIT',
		'NUEVO LEON',
		'OAXACA',
		'PUEBLA',
		'QUINTANA ROO',
		'QUERETARO',
		'SAN LUIS POTOSI',
		'SINALOA',
		'SONORA',
		'TABASCO',
		'TAMAULIPAS',
		'VERACRUZ',
		'YUCATAN',
		'GOIAS',
		'TOLIMA',
		'LA HABANA',
		'CALIFORNIA',
		'COLORADO',
		'FLORIDA',
		'TEXAS',
		'CORTES',
		'MOSCU', // 🔥 Agregado
		'MOGADISCIO',
	]

	for (const state of stateNames) {
		const result = await prisma.states.findFirst({ where: { name: state } })
		if (result) stateMap.set(state, result.id)
	}

	const data = [
		{ name: 'AXOCHIAPAN', stateId: stateMap.get('MORELOS') },
		{ name: 'CIVAC', stateId: stateMap.get('MORELOS') },
		{ name: 'CUAUTLA', stateId: stateMap.get('MORELOS') },
		{ name: 'CUERNAVACA', stateId: stateMap.get('MORELOS') },
		{ name: 'EMILIANO ZAPATA', stateId: stateMap.get('MORELOS') },
		{ name: 'HUEYAPAN', stateId: stateMap.get('MORELOS') },
		{ name: 'HUITZILAC', stateId: stateMap.get('MORELOS') },
		{ name: 'JANTETELCO', stateId: stateMap.get('MORELOS') },
		{ name: 'JIUTEPEC', stateId: stateMap.get('MORELOS') },
		{ name: 'JOJUTLA', stateId: stateMap.get('MORELOS') },
		{ name: 'MAZATEPEC', stateId: stateMap.get('MORELOS') },
		{ name: 'OACALCO', stateId: stateMap.get('MORELOS') },
		{ name: 'OAXTEPEC', stateId: stateMap.get('MORELOS') },
		{ name: 'PUENTE DE IXTLA', stateId: stateMap.get('MORELOS') },
		{ name: 'TEMIXCO', stateId: stateMap.get('MORELOS') },
		{ name: 'TEMOAC', stateId: stateMap.get('MORELOS') },
		{ name: 'TEPALCINGO', stateId: stateMap.get('MORELOS') },
		{ name: 'TEPOZTLAN', stateId: stateMap.get('MORELOS') },
		{ name: 'TEHUIXTLA', stateId: stateMap.get('MORELOS') },
		{ name: 'TLAQUILTENANGO', stateId: stateMap.get('MORELOS') },
		{ name: 'XOCHITEPEC', stateId: stateMap.get('MORELOS') },
		{ name: 'XOXOCOTLA', stateId: stateMap.get('MORELOS') },
		{ name: 'YAUTEPEC', stateId: stateMap.get('MORELOS') },
		{ name: 'ZACATEPEC', stateId: stateMap.get('MORELOS') },
		{ name: 'ATLATLAHUCAN', stateId: stateMap.get('MORELOS') },
		{ name: 'CIUDAD DE MEXICO', stateId: stateMap.get('CIUDAD DE MEXICO') },
		{ name: 'ACAPULCO', stateId: stateMap.get('GUERRERO') },
		{ name: 'ARCELIA', stateId: stateMap.get('GUERRERO') },
		{ name: 'BUENAVISTA DE CUELLAR', stateId: stateMap.get('GUERRERO') },
		{ name: 'CHILAPA', stateId: stateMap.get('GUERRERO') },
		{ name: 'CHILPANCINGO', stateId: stateMap.get('GUERRERO') },
		{ name: 'COSTA CHICA', stateId: stateMap.get('GUERRERO') },
		{ name: 'COYUCA DE CATALAN', stateId: stateMap.get('GUERRERO') },
		{ name: 'HUITZUCO', stateId: stateMap.get('GUERRERO') },
		{ name: 'IGUALA DE LA INDEPENDENCIA', stateId: stateMap.get('GUERRERO') },
		{ name: 'OMOTEPEC', stateId: stateMap.get('GUERRERO') },
		{ name: 'TAXCO', stateId: stateMap.get('GUERRERO') },
		{ name: 'TETIPAC', stateId: stateMap.get('GUERRERO') },
		{ name: 'ESTADO DE MEXICO', stateId: stateMap.get('ESTADO DE MEXICO') },
		{ name: 'HUIXQUILUCAN', stateId: stateMap.get('ESTADO DE MEXICO') },
		{ name: 'NEZAHUALCOYOTL', stateId: stateMap.get('ESTADO DE MEXICO') },
		{ name: 'OCUILAN', stateId: stateMap.get('ESTADO DE MEXICO') },
		{
			name: 'SANTIAGO TIANGUISTENCO',
			stateId: stateMap.get('ESTADO DE MEXICO'),
		},
		{ name: 'TENANCINGO', stateId: stateMap.get('ESTADO DE MEXICO') },
		{ name: 'TEZOYUCA', stateId: stateMap.get('ESTADO DE MEXICO') },
		{ name: 'TOLUCA', stateId: stateMap.get('ESTADO DE MEXICO') },
		{ name: 'AGUASCALIENTES', stateId: stateMap.get('AGUASCALIENTES') },
		{ name: 'ENSENADA', stateId: stateMap.get('BAJA CALIFORNIA') },
		{ name: 'TIJUANA', stateId: stateMap.get('BAJA CALIFORNIA') },
		{ name: 'LORETO', stateId: stateMap.get('BAJA CALIFORNIA SUR') },
		{ name: 'CIUDAD DEL CARMEN', stateId: stateMap.get('CAMPECHE') },
		{ name: 'SAN CRISTOBAL DE LAS CASAS', stateId: stateMap.get('CHIAPAS') },
		{ name: 'GOMEZ PALACIOS', stateId: stateMap.get('COAHUILA DE ZARAGOZA') },
		{ name: 'PIEDRAS NEGRAS', stateId: stateMap.get('COAHUILA DE ZARAGOZA') },
		{ name: 'SALTILLO', stateId: stateMap.get('COAHUILA DE ZARAGOZA') },
		{ name: 'GOMEZ PALACIOS', stateId: stateMap.get('DURANGO') },
		{ name: 'GUANAJUATO', stateId: stateMap.get('GUANAJUATO') },
		{ name: 'LEON', stateId: stateMap.get('GUANAJUATO') },
		{ name: 'HIDALGO', stateId: stateMap.get('HIDALGO') },
		{ name: 'PACHUCA', stateId: stateMap.get('HIDALGO') },
		{ name: 'GUADALAJARA', stateId: stateMap.get('JALISCO') },
		{ name: 'ZAPOPAN', stateId: stateMap.get('JALISCO') },
		{ name: 'MORELIA', stateId: stateMap.get('MICHOACAN') },
		{ name: 'SANTIAGO IXCUINTLA', stateId: stateMap.get('NAYARIT') },
		{ name: 'MONTERREY', stateId: stateMap.get('NUEVO LEON') },
		{ name: 'OAXACA', stateId: stateMap.get('OAXACA') },
		{ name: 'AMOZOC DE PUEBLA', stateId: stateMap.get('PUEBLA') },
		{ name: 'CHOLULA', stateId: stateMap.get('PUEBLA') },
		{ name: 'PUEBLA', stateId: stateMap.get('PUEBLA') },
		{ name: 'TEPEXI DE RODRIGUEZ', stateId: stateMap.get('PUEBLA') },
		{ name: 'CANCUN', stateId: stateMap.get('QUINTANA ROO') },
		{ name: 'QUERETARO', stateId: stateMap.get('QUERETARO') },
		{ name: 'SAN LUIS POTOSI', stateId: stateMap.get('SAN LUIS POTOSI') },
		{ name: 'CULIACAN', stateId: stateMap.get('SINALOA') },
		{ name: 'LOS MOCHIS', stateId: stateMap.get('SINALOA') },
		{ name: 'OBREGON', stateId: stateMap.get('SONORA') },
		{ name: 'VILLAHERMOSA', stateId: stateMap.get('TABASCO') },
		{ name: 'MADERO', stateId: stateMap.get('TAMAULIPAS') },
		{ name: 'CERRO AZUL', stateId: stateMap.get('VERACRUZ') },
		{ name: 'VERACRUZ', stateId: stateMap.get('VERACRUZ') },
		{ name: 'MERIDA', stateId: stateMap.get('YUCATAN') },
		{ name: 'GOIANIA', stateId: stateMap.get('GOIAS') },
		{ name: 'IBAGUE', stateId: stateMap.get('TOLIMA') },
		{ name: 'HABANA CUBA', stateId: stateMap.get('LA HABANA') },
		{ name: 'CALIFORNIA', stateId: stateMap.get('CALIFORNIA') },
		{ name: 'COLORADO', stateId: stateMap.get('COLORADO') },
		{ name: 'FLORIDA', stateId: stateMap.get('FLORIDA') },
		{ name: 'AUSTIN', stateId: stateMap.get('TEXAS') },
		{ name: 'TEXAS', stateId: stateMap.get('TEXAS') },
		{ name: 'SAN PEDRO SULA', stateId: stateMap.get('CORTES') },
		{ name: 'MOSCU', stateId: stateMap.get('MOSCU') },
		{ name: 'MOGADISHU', stateId: stateMap.get('MOGADISCIO') },
	]
	const invalid = data.filter((d) => !d.stateId)
	if (invalid.length > 0) {
		console.error('❌ Las siguientes ciudades no tienen `stateId` válido:')
		console.table(invalid)
		throw new Error(
			'🚫 No se puede ejecutar createMany con `stateId` undefined.',
		)
	}

	await prisma.cities.createMany({ data, skipDuplicates: true })
}
