import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function StatesSeeder() {
  const [
    country1,
    country2,
    country3,
    country4,
    country5,
    country6,
    country7,
    country8,
    country9,
    country10,
    country11,
    country12,
    country13,
    country14
  ] = await Promise.all([
    prisma.countries.findFirst({ where: { name: 'MEXICO' } }),
    prisma.countries.findFirst({ where: { name: 'ESTADOS UNIDOS' } }),
    prisma.countries.findFirst({ where: { name: 'CUBA' } }),
    prisma.countries.findFirst({ where: { name: 'COLOMBIA' } }),
    prisma.countries.findFirst({ where: { name: 'SOMALIA' } }),
    prisma.countries.findFirst({ where: { name: 'BRASIL' } }),
    prisma.countries.findFirst({ where: { name: 'VENEZUELA' } }),
    prisma.countries.findFirst({ where: { name: 'RUSIA' } }),
    prisma.countries.findFirst({ where: { name: 'PORTUGAL' } }),
    prisma.countries.findFirst({ where: { name: 'ESPAÑA' } }),
    prisma.countries.findFirst({ where: { name: 'HONDURAS' } }),
    prisma.countries.findFirst({ where: { name: 'PANAMA' } }),
    prisma.countries.findFirst({ where: { name: 'CHILE' } }),
    prisma.countries.findFirst({ where: { name: 'PERU' } })
  ]);

  const countryMap = {
    'MEXICO': country1.id,
    'ESTADOS UNIDOS': country2.id,
    'CUBA': country3.id,
    'COLOMBIA': country4.id,
    'SOMALIA': country5.id,
    'BRASIL': country6.id,
    'VENEZUELA': country7.id,
    'RUSIA': country8.id,
    'PORTUGAL': country9.id,
    'ESPAÑA': country10.id,
    'HONDURAS': country11.id,
    'PANAMA': country12.id,
    'CHILE': country13.id,
    'PERU': country14.id,
  };

  const getCountryId = (name) => countryMap[name];

  const data = [
  { name: 'AGUASCALIENTES', countryId: getCountryId('MEXICO') },
  { name: 'BAJA CALIFORNIA', countryId: getCountryId('MEXICO') },
  { name: 'BAJA CALIFORNIA SUR', countryId: getCountryId('MEXICO') },
  { name: 'CAMPECHE', countryId: getCountryId('MEXICO') },
  { name: 'CHIAPAS', countryId: getCountryId('MEXICO') },
  { name: 'CHIHUAHUA', countryId: getCountryId('MEXICO') },
  { name: 'CIUDAD DE MEXICO', countryId: getCountryId('MEXICO') },
  { name: 'COAHUILA DE ZARAGOZA', countryId: getCountryId('MEXICO') },
  { name: 'COLIMA', countryId: getCountryId('MEXICO') },
  { name: 'DURANGO', countryId: getCountryId('MEXICO') },
  { name: 'ESTADO DE MEXICO', countryId: getCountryId('MEXICO') },
  { name: 'GUANAJUATO', countryId: getCountryId('MEXICO') },
  { name: 'GUERRERO', countryId: getCountryId('MEXICO') },
  { name: 'HIDALGO', countryId: getCountryId('MEXICO') },
  { name: 'JALISCO', countryId: getCountryId('MEXICO') },
  { name: 'MICHOACAN', countryId: getCountryId('MEXICO') },
  { name: 'MORELOS', countryId: getCountryId('MEXICO') },
  { name: 'NAYARIT', countryId: getCountryId('MEXICO') },
  { name: 'NUEVO LEON', countryId: getCountryId('MEXICO') },
  { name: 'OAXACA', countryId: getCountryId('MEXICO') },
  { name: 'PUEBLA', countryId: getCountryId('MEXICO') },
  { name: 'QUERETARO', countryId: getCountryId('MEXICO') },
  { name: 'QUINTANA ROO', countryId: getCountryId('MEXICO') },
  { name: 'SAN LUIS POTOSI', countryId: getCountryId('MEXICO') },
  { name: 'SINALOA', countryId: getCountryId('MEXICO') },
  { name: 'SONORA', countryId: getCountryId('MEXICO') },
  { name: 'TABASCO', countryId: getCountryId('MEXICO') },
  { name: 'TAMAULIPAS', countryId: getCountryId('MEXICO') },
  { name: 'TLAXCALA', countryId: getCountryId('MEXICO') },
  { name: 'VERACRUZ', countryId: getCountryId('MEXICO') },
  { name: 'YUCATAN', countryId: getCountryId('MEXICO') },
  { name: 'ZACATECAS', countryId: getCountryId('MEXICO') },
    { name: 'ALABAMA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'ALASKA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'ARIZONA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'ARKANSAS', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'CALIFORNIA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'CAROLINA DEL NORTE', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'CAROLINA DEL SUR', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'COLORADO', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'CONNECTICUT', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'DAKOTA DEL NORTE', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'DAKOTA DEL SUR', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'DELAWARE', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'FLORIDA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'GEORGIA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'HAWAI', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'IDAHO', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'ILLINOIS', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'INDIANA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'IOWA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'KANSAS', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'KENTUCKY', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'LUISIANA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MAINE', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MARYLAND', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MASSACHUSETTS', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MICHIGAN', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MINNESOTA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MISISIPI', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MISURI', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'MONTANA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'NEBRASKA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'NEVADA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'NUEVO HAMPSHIRE', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'NUEVA JERSEY', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'NUEVO MEXICO', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'NUEVA YORK', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'OHIO', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'OKLAHOMA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'OREGON', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'PENSILVANIA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'RHODE ISLAND', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'TENNESSEE', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'TEXAS', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'UTAH', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'VERMONT', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'VIRGINIA', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'VIRGINIA OCCIDENTAL', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'WASHINGTON', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'WISCONSIN', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'WYOMING', countryId: getCountryId('ESTADOS UNIDOS') },
    { name: 'ARTEMISA', countryId: getCountryId('CUBA') },
    { name: 'CAMAGUEY', countryId: getCountryId('CUBA') },
    { name: 'CIEGO DE AVILA', countryId: getCountryId('CUBA') },
    { name: 'CIENFUEGOS', countryId: getCountryId('CUBA') },
    { name: 'GRANMA', countryId: getCountryId('CUBA') },
    { name: 'GUANTANAMO', countryId: getCountryId('CUBA') },
    { name: 'HOLGUIN', countryId: getCountryId('CUBA') },
    { name: 'ISLA DE LA JUVENTUD', countryId: getCountryId('CUBA') },
    { name: 'LA HABANA', countryId: getCountryId('CUBA') },
    { name: 'LAS TUNAS', countryId: getCountryId('CUBA') },
    { name: 'MATANZAS', countryId: getCountryId('CUBA') },
    { name: 'MAYABEQUE', countryId: getCountryId('CUBA') },
    { name: 'PINAR DEL RIO', countryId: getCountryId('CUBA') },
    { name: 'SANCTI SPIRITUS', countryId: getCountryId('CUBA') },
    { name: 'SANTIAGO DE CUBA', countryId: getCountryId('CUBA') },
    { name: 'VILLA CLARA', countryId: getCountryId('CUBA') },
    { name: 'AMAZONAS', countryId: getCountryId('COLOMBIA') },
    { name: 'ANTIOQUIA', countryId: getCountryId('COLOMBIA') },
    { name: 'ARAUCA', countryId: getCountryId('COLOMBIA') },
    { name: 'ATLANTICO', countryId: getCountryId('COLOMBIA') },
    { name: 'BOLIVAR', countryId: getCountryId('COLOMBIA') },
    { name: 'BOYACA', countryId: getCountryId('COLOMBIA') },
    { name: 'CALDAS', countryId: getCountryId('COLOMBIA') },
    { name: 'CAQUETA', countryId: getCountryId('COLOMBIA') },
    { name: 'CASANARE', countryId: getCountryId('COLOMBIA') },
    { name: 'CAUCA', countryId: getCountryId('COLOMBIA') },
    { name: 'CESAR', countryId: getCountryId('COLOMBIA') },
    { name: 'CHOCO', countryId: getCountryId('COLOMBIA') },
    { name: 'CORDOBA', countryId: getCountryId('COLOMBIA') },
    { name: 'CUNDINAMARCA', countryId: getCountryId('COLOMBIA') },
    { name: 'GUAINIA', countryId: getCountryId('COLOMBIA') },
    { name: 'GUAVIARE', countryId: getCountryId('COLOMBIA') },
    { name: 'HUILA', countryId: getCountryId('COLOMBIA') },
    { name: 'LA GUAJIRA', countryId: getCountryId('COLOMBIA') },
    { name: 'MAGDALENA', countryId: getCountryId('COLOMBIA') },
    { name: 'META', countryId: getCountryId('COLOMBIA') },
    { name: 'NARINO', countryId: getCountryId('COLOMBIA') },
    { name: 'NORTE DE SANTANDER', countryId: getCountryId('COLOMBIA') },
    { name: 'PUTUMAYO', countryId: getCountryId('COLOMBIA') },
    { name: 'QUINDIO', countryId: getCountryId('COLOMBIA') },
    { name: 'RISARALDA', countryId: getCountryId('COLOMBIA') },
    { name: 'SAN ANDRES Y PROVIDENCIA', countryId: getCountryId('COLOMBIA') },
    { name: 'SANTANDER', countryId: getCountryId('COLOMBIA') },
    { name: 'SUCRE', countryId: getCountryId('COLOMBIA') },
    { name: 'TOLIMA', countryId: getCountryId('COLOMBIA') },
    { name: 'VALLE DEL CAUCA', countryId: getCountryId('COLOMBIA') },
    { name: 'VAUPES', countryId: getCountryId('COLOMBIA') },
    { name: 'VICHADA', countryId: getCountryId('COLOMBIA') },
    { name: 'GALMUDUG', countryId: getCountryId('SOMALIA') },
    { name: 'HIRSHABELLE', countryId: getCountryId('SOMALIA') },
    { name: 'JUBALAND', countryId: getCountryId('SOMALIA') },
    { name: 'SOMALILANDIA', countryId: getCountryId('SOMALIA') },
    { name: 'PUNTLANDIA', countryId: getCountryId('SOMALIA') },
    { name: 'SUROESTE', countryId: getCountryId('SOMALIA') },
    { name: 'MOGADISCIO', countryId: getCountryId('SOMALIA') },
    { name: 'ACRE', countryId: getCountryId('BRASIL') },
    { name: 'ALAGOAS', countryId: getCountryId('BRASIL') },
    { name: 'AMAPA', countryId: getCountryId('BRASIL') },
    { name: 'AMAZONAS', countryId: getCountryId('BRASIL') },
    { name: 'BAHIA', countryId: getCountryId('BRASIL') },
    { name: 'CEARA', countryId: getCountryId('BRASIL') },
    { name: 'DISTRITO FEDERAL', countryId: getCountryId('BRASIL') },
    { name: 'ESPIRITO SANTO', countryId: getCountryId('BRASIL') },
    { name: 'GOIAS', countryId: getCountryId('BRASIL') },
    { name: 'MARANHAO', countryId: getCountryId('BRASIL') },
    { name: 'MATO GROSSO', countryId: getCountryId('BRASIL') },
    { name: 'MATO GROSSO DEL SUR', countryId: getCountryId('BRASIL') },
    { name: 'MINAS GERAIS', countryId: getCountryId('BRASIL') },
    { name: 'PARA', countryId: getCountryId('BRASIL') },
    { name: 'PARAIBA', countryId: getCountryId('BRASIL') },
    { name: 'PARANA', countryId: getCountryId('BRASIL') },
    { name: 'PERNAMBUCO', countryId: getCountryId('BRASIL') },
    { name: 'PIAUI', countryId: getCountryId('BRASIL') },
    { name: 'RIO DE JANEIRO', countryId: getCountryId('BRASIL') },
    { name: 'RIO GRANDE DEL NORTE', countryId: getCountryId('BRASIL') },
    { name: 'RIO GRANDE DEL SUR', countryId: getCountryId('BRASIL') },
    { name: 'RONDONIA', countryId: getCountryId('BRASIL') },
    { name: 'RORAIMA', countryId: getCountryId('BRASIL') },
    { name: 'SANTA CATARINA', countryId: getCountryId('BRASIL') },
    { name: 'SAO PAULO', countryId: getCountryId('BRASIL') },
    { name: 'SERGIPE', countryId: getCountryId('BRASIL') },
    { name: 'TOCANTINS', countryId: getCountryId('BRASIL') },
    { name: 'AMAZONAS', countryId: getCountryId('VENEZUELA') },
    { name: 'ANZOATEGUI', countryId: getCountryId('VENEZUELA') },
    { name: 'APURE', countryId: getCountryId('VENEZUELA') },
    { name: 'ARAGUA', countryId: getCountryId('VENEZUELA') },
    { name: 'BARINAS', countryId: getCountryId('VENEZUELA') },
    { name: 'BOLIVAR', countryId: getCountryId('VENEZUELA') },
    { name: 'CARABOBO', countryId: getCountryId('VENEZUELA') },
    { name: 'COJEDES', countryId: getCountryId('VENEZUELA') },
    { name: 'DELTA AMACURO', countryId: getCountryId('VENEZUELA') },
    { name: 'DISTRITO CAPITAL', countryId: getCountryId('VENEZUELA') },
    { name: 'FALCON', countryId: getCountryId('VENEZUELA') },
    { name: 'GUARICO', countryId: getCountryId('VENEZUELA') },
    { name: 'LARA', countryId: getCountryId('VENEZUELA') },
    { name: 'MERIDA', countryId: getCountryId('VENEZUELA') },
    { name: 'MIRANDA', countryId: getCountryId('VENEZUELA') },
    { name: 'MONAGAS', countryId: getCountryId('VENEZUELA') },
    { name: 'NUEVA ESPARTA', countryId: getCountryId('VENEZUELA') },
    { name: 'PORTUGUESA', countryId: getCountryId('VENEZUELA') },
    { name: 'SUCRE', countryId: getCountryId('VENEZUELA') },
    { name: 'TACHIRA', countryId: getCountryId('VENEZUELA') },
    { name: 'TRUJILLO', countryId: getCountryId('VENEZUELA') },
    { name: 'VARGAS', countryId: getCountryId('VENEZUELA') },
    { name: 'YARACUY', countryId: getCountryId('VENEZUELA') },
    { name: 'ZULIA', countryId: getCountryId('VENEZUELA') },
    { name: 'ADIGUEYA', countryId: getCountryId('RUSIA') },
    { name: 'ALTAI', countryId: getCountryId('RUSIA') },
    { name: 'BASKORTOSTAN', countryId: getCountryId('RUSIA') },
    { name: 'BURIATIA', countryId: getCountryId('RUSIA') },
    { name: 'CHECHENIA', countryId: getCountryId('RUSIA') },
    { name: 'CHUVASIA', countryId: getCountryId('RUSIA') },
    { name: 'DAGUESTAN', countryId: getCountryId('RUSIA') },
    { name: 'INGUSETIA', countryId: getCountryId('RUSIA') },
    { name: 'KABARDINO-BALKARIA', countryId: getCountryId('RUSIA') },
    { name: 'KALMUKIA', countryId: getCountryId('RUSIA') },
    { name: 'KARACHAYEVO-CHERKESIA', countryId: getCountryId('RUSIA') },
    { name: 'KARELIA', countryId: getCountryId('RUSIA') },
    { name: 'JAKASIA', countryId: getCountryId('RUSIA') },
    { name: 'KOMI', countryId: getCountryId('RUSIA') },
    { name: 'MARI EL', countryId: getCountryId('RUSIA') },
    { name: 'MORDOVIA', countryId: getCountryId('RUSIA') },
    { name: 'OSETIA DEL NORTE-ALANIA', countryId: getCountryId('RUSIA') },
    { name: 'TARTARISTAN', countryId: getCountryId('RUSIA') },
    { name: 'TUVA', countryId: getCountryId('RUSIA') },
    { name: 'UDMURTIA', countryId: getCountryId('RUSIA') },
    { name: 'YAKUTIA', countryId: getCountryId('RUSIA') },
    { name: 'MOSCU', countryId: getCountryId('RUSIA') },
    { name: 'LENINGRADO', countryId: getCountryId('RUSIA') },
    { name: 'SVERDLOVSK', countryId: getCountryId('RUSIA') },
    { name: 'ALTAY', countryId: getCountryId('RUSIA') },
    { name: 'KRASNODAR', countryId: getCountryId('RUSIA') },
    { name: 'SAN PETERSBURGO', countryId: getCountryId('RUSIA') },
    { name: 'SEBASTOPOL', countryId: getCountryId('RUSIA') },
    { name: 'CHUKOTKA', countryId: getCountryId('RUSIA') },
    { name: 'JANTI-MANSI', countryId: getCountryId('RUSIA') },
    { name: 'NENETSIA', countryId: getCountryId('RUSIA') },
    { name: 'YAMALO-NENETS', countryId: getCountryId('RUSIA') },
    { name: 'AVEIRO', countryId: getCountryId('PORTUGAL') },
    { name: 'BEJA', countryId: getCountryId('PORTUGAL') },
    { name: 'BRAGA', countryId: getCountryId('PORTUGAL') },
    { name: 'BRAGANCA', countryId: getCountryId('PORTUGAL') },
    { name: 'CASTELO BRANCO', countryId: getCountryId('PORTUGAL') },
    { name: 'COIMBRA', countryId: getCountryId('PORTUGAL') },
    { name: 'EVORA', countryId: getCountryId('PORTUGAL') },
    { name: 'FARO', countryId: getCountryId('PORTUGAL') },
    { name: 'GUARDA', countryId: getCountryId('PORTUGAL') },
    { name: 'LEIRIA', countryId: getCountryId('PORTUGAL') },
    { name: 'LISBOA', countryId: getCountryId('PORTUGAL') },
    { name: 'PORTALEGRE', countryId: getCountryId('PORTUGAL') },
    { name: 'PORTO', countryId: getCountryId('PORTUGAL') },
    { name: 'SANTAREM', countryId: getCountryId('PORTUGAL') },
    { name: 'SETUBAL', countryId: getCountryId('PORTUGAL') },
    { name: 'VIANA DO CASTELO', countryId: getCountryId('PORTUGAL') },
    { name: 'VILA REAL', countryId: getCountryId('PORTUGAL') },
    { name: 'VISEU', countryId: getCountryId('PORTUGAL') },
    { name: 'AZORES', countryId: getCountryId('PORTUGAL') },
    { name: 'MADEIRA', countryId: getCountryId('PORTUGAL') },
    { name: 'ANDALUCIA', countryId: getCountryId('ESPAÑA') },
    { name: 'ARAGON', countryId: getCountryId('ESPAÑA') },
    { name: 'ASTURIAS', countryId: getCountryId('ESPAÑA') },
    { name: 'ISLAS BALEARES', countryId: getCountryId('ESPAÑA') },
    { name: 'PAIS VASCO', countryId: getCountryId('ESPAÑA') },
    { name: 'ISLAS CANARIAS', countryId: getCountryId('ESPAÑA') },
    { name: 'CANTABRIA', countryId: getCountryId('ESPAÑA') },
    { name: 'CASTILLA Y LEON', countryId: getCountryId('ESPAÑA') },
    { name: 'CASTILLA-LA MANCHA', countryId: getCountryId('ESPAÑA') },
    { name: 'CATALUNA', countryId: getCountryId('ESPAÑA') },
    { name: 'COMUNIDAD DE MADRID', countryId: getCountryId('ESPAÑA') },
    { name: 'EXTREMADURA', countryId: getCountryId('ESPAÑA') },
    { name: 'GALICIA', countryId: getCountryId('ESPAÑA') },
    { name: 'LA RIOJA', countryId: getCountryId('ESPAÑA') },
    { name: 'REGION DE MURCIA', countryId: getCountryId('ESPAÑA') },
    { name: 'NAVARRA', countryId: getCountryId('ESPAÑA') },
    { name: 'COMUNIDAD VALENCIANA', countryId: getCountryId('ESPAÑA') },
    { name: 'CEUTA', countryId: getCountryId('ESPAÑA') },
    { name: 'MELILLA', countryId: getCountryId('ESPAÑA') },
    { name: 'ATLANTIDA', countryId: getCountryId('HONDURAS') },
    { name: 'CHOLUTECA', countryId: getCountryId('HONDURAS') },
    { name: 'COLON', countryId: getCountryId('HONDURAS') },
    { name: 'COMAYAGUA', countryId: getCountryId('HONDURAS') },
    { name: 'COPAN', countryId: getCountryId('HONDURAS') },
    { name: 'CORTES', countryId: getCountryId('HONDURAS') },
    { name: 'EL PARAISO', countryId: getCountryId('HONDURAS') },
    { name: 'FRANCISCO MORAZAN', countryId: getCountryId('HONDURAS') },
    { name: 'GRACIAS A DIOS', countryId: getCountryId('HONDURAS') },
    { name: 'INTIBUCA', countryId: getCountryId('HONDURAS') },
    { name: 'ISLAS DE LA BAHIA', countryId: getCountryId('HONDURAS') },
    { name: 'LA PAZ', countryId: getCountryId('HONDURAS') },
    { name: 'LEMPIRA', countryId: getCountryId('HONDURAS') },
    { name: 'OCOTEPEQUE', countryId: getCountryId('HONDURAS') },
    { name: 'OLANCHO', countryId: getCountryId('HONDURAS') },
    { name: 'SANTA BARBARA', countryId: getCountryId('HONDURAS') },
    { name: 'VALLE', countryId: getCountryId('HONDURAS') },
    { name: 'YORO', countryId: getCountryId('HONDURAS') },
    { name: 'BOCAS DEL TORO', countryId: getCountryId('PANAMA') },
    { name: 'CHIRIQUI', countryId: getCountryId('PANAMA') },
    { name: 'COCLE', countryId: getCountryId('PANAMA') },
    { name: 'COLON', countryId: getCountryId('PANAMA') },
    { name: 'DARIEN', countryId: getCountryId('PANAMA') },
    { name: 'HERRERA', countryId: getCountryId('PANAMA') },
    { name: 'LOS SANTOS', countryId: getCountryId('PANAMA') },
    { name: 'PANAMA', countryId: getCountryId('PANAMA') },
    { name: 'PANAMA OESTE', countryId: getCountryId('PANAMA') },
    { name: 'VERAGUAS', countryId: getCountryId('PANAMA') },
    { name: 'EMBERA-WOUNAAN', countryId: getCountryId('PANAMA') },
    { name: 'GUNA DE MADUNGANDI', countryId: getCountryId('PANAMA') },
    { name: 'GUNA DE WARGANDI', countryId: getCountryId('PANAMA') },
    { name: 'GUNA YALA', countryId: getCountryId('PANAMA') },
    { name: 'NGABE-BUGLE', countryId: getCountryId('PANAMA') },
    { name: 'NASO TJER DI', countryId: getCountryId('PANAMA') },
    { name: 'ARICA Y PARINACOTA', countryId: getCountryId('CHILE') },
    { name: 'TARAPACA', countryId: getCountryId('CHILE') },
    { name: 'ANTOFAGASTA', countryId: getCountryId('CHILE') },
    { name: 'ATACAMA', countryId: getCountryId('CHILE') },
    { name: 'COQUIMBO', countryId: getCountryId('CHILE') },
    { name: 'VALPARAISO', countryId: getCountryId('CHILE') },
    { name: 'METROPOLITANA DE SANTIAGO', countryId: getCountryId('CHILE') },
    { name: 'O HIGGINS', countryId: getCountryId('CHILE') },
    { name: 'MAULE', countryId: getCountryId('CHILE') },
    { name: 'NUBLE', countryId: getCountryId('CHILE') },
    { name: 'BIOBIO', countryId: getCountryId('CHILE') },
    { name: 'LA ARAUCANIA', countryId: getCountryId('CHILE') },
    { name: 'LOS RIOS', countryId: getCountryId('CHILE') },
    { name: 'LOS LAGOS', countryId: getCountryId('CHILE') },
    { name: 'AYSEN DEL GENERAL CARLOS IBANEZ DEL CAMPO', countryId: getCountryId('CHILE') },
    { name: 'MAGALLANES Y LA ANTARTICA CHILENA', countryId: getCountryId('CHILE') },
    { name: 'AMAZONAS', countryId: getCountryId('PERU') },
    { name: 'ANCASH', countryId: getCountryId('PERU') },
    { name: 'APURIMAC', countryId: getCountryId('PERU') },
    { name: 'AREQUIPA', countryId: getCountryId('PERU') },
    { name: 'AYACUCHO', countryId: getCountryId('PERU') },
    { name: 'CAJAMARCA', countryId: getCountryId('PERU') },
    { name: 'CUSCO', countryId: getCountryId('PERU') },
    { name: 'HUANCAVELICA', countryId: getCountryId('PERU') },
    { name: 'HUANUCO', countryId: getCountryId('PERU') },
    { name: 'ICA', countryId: getCountryId('PERU') },
    { name: 'JUNIN', countryId: getCountryId('PERU') },
    { name: 'LA LIBERTAD', countryId: getCountryId('PERU') },
    { name: 'LAMBAYEQUE', countryId: getCountryId('PERU') },
    { name: 'LIMA', countryId: getCountryId('PERU') },
    { name: 'LORETO', countryId: getCountryId('PERU') },
    { name: 'MADRE DE DIOS', countryId: getCountryId('PERU') },
    { name: 'MOQUEGUA', countryId: getCountryId('PERU') },
    { name: 'PASCO', countryId: getCountryId('PERU') },
    { name: 'PIURA', countryId: getCountryId('PERU') },
    { name: 'PUNO', countryId: getCountryId('PERU') },
    { name: 'SAN MARTIN', countryId: getCountryId('PERU') },
    { name: 'TACNA', countryId: getCountryId('PERU') },
    { name: 'TUMBES', countryId: getCountryId('PERU') },
    { name: 'UCAYALI', countryId: getCountryId('PERU') },
    { name: 'CALLAO', countryId: getCountryId('PERU') },
  ];

  await prisma.states.createMany({ data, skipDuplicates: true });
}